MODULE NUMBER_TYPES
IMPLICIT NONE
!!$
!!$ INTRISIC DATA TYPES KIND PARAMETERS
!!$
!!$ INTEGERS
  INTEGER,PARAMETER :: I4B  = SELECTED_INT_KIND(9)
  INTEGER,PARAMETER :: I2B  = SELECTED_INT_KIND(4)
  INTEGER,PARAMETER :: I1B  = SELECTED_INT_KIND(2)
!!$ REAL SINGLE PRECISION
  INTEGER,PARAMETER :: SP  = KIND(1.0)
!!$ REAL DOUBLE PRECISION
  INTEGER,PARAMETER :: DP  = KIND(1.D0)
!!$ COMPLEX
  INTEGER,PARAMETER :: CSP = KIND((1.0,1.0))
  INTEGER,PARAMETER :: CDP = KIND((1.0_DP,1.0_DP))

!!$ Select floating pointing type for stereotomography 
  INTEGER,PARAMETER::fp = sp;

END MODULE NUMBER_TYPES
